#!/usr/bin/env bash

create_symlinks () {
  ln -s $HOME/bin/binwarden/secrets-managers/* $HOME/bin/binwarden/
  ln -s $HOME/bin/binwarden/cloners/* $HOME/bin/binwarden/
  ln -s $HOME/bin/binwarden/installers/* $HOME/bin/binwarden/
  ln -s $HOME/bin/binwarden/starters/* $HOME/bin/binwarden/
  ln -s $HOME/bin/binwarden/runners/* $HOME/bin/binwarden/
  ln -s $HOME/bin/binwarden/helpers/* $HOME/bin/binwarden/
  ln -s $HOME/bin/binwarden/dev/* $HOME/bin/binwarden/
}

create_symlinks
