#!/usr/bin/env bash

source $HOME/bin/binwarden/windows/windows-core ${1}

if [ $SUPPORTS_DESTROY == false ] 
then
  log_error "$PROJECT_NAME does not support destruction operations."
else
  WINDOW_NAME="Destroy"
  STARTER_COMMAND="${DESTROY_COMMAND}; tail -f /dev/null"
  start_window
fi

