#!/usr/bin/env bash

source $HOME/bin/binwarden/windows/windows-core ${1}

if [ $SUPPORTS_GIT == false ] 
then
  log_error "$PROJECT_NAME does not support git operations."
else
  WINDOW_NAME="Git"
  STARTER_COMMAND="cd $PROJECT_PATH; lazygit"

  ensure_command_installed lazygit
  start_window
fi

