#!/usr/bin/env bash

CONTAINERNAME=bitwardenserver-mssql-1
COMPOSEPROFILENAME=mssql
LOGFILENAME=bw-docker-mssql.log

ensure_project_ready () {
  if [ ! -d "$HOME/bitwarden/server" ]; then
    bw-build-server
  fi

  if [ ! -d "$HOME/bitwarden/logs" ]; then
    cd $HOME/bitwarden
    mkdir logs
  fi

  rm -f $HOME/bitwarden/logs/$LOGFILENAME
  touch $HOME/bitwarden/logs/$LOGFILENAME
}

start () {
  ensure_project_ready
  cd $HOME/bitwarden/server/dev
  if [ ! "$(docker ps | grep $CONTAINERNAME)" ]; then
    docker compose --profile $COMPOSEPROFILENAME up -d 2>&1 | tee -a $HOME/bitwarden/logs/$LOGFILENAME
  fi
}

start
