#!/usr/bin/env bash

ensure_project_ready () {
  if [ ! -d "$HOME/bitwarden/clients" ]; then
    bw-scaffold-clients
    bw-build-web
  fi

  if [ ! -d "$HOME/bitwarden/logs" ]; then
    cd $HOME/bitwarden
    mkdir logs
  fi

  rm -f $HOME/bitwarden/logs/bw-web.log
  touch $HOME/bitwarden/logs/bw-web.log
}

install_packages () {
  cd $HOME/bitwarden/clients
  rm -rf node_modules
  npm ci
}

start_project () {
  cd $HOME/bitwarden/clients/apps/web
  npm run build:bit:dev:watch > $HOME/bitwarden/logs/bw-web.log
}

start_web () {
  ensure_project_ready
  #install_packages
  start_project
}

start_web
