#!/usr/bin/env bash

source core

ensure_project_ready () {
  if [ ! -d "$HOME/bitwarden/server" ]; then
    bw-build-server
  fi

  if [ ! -d "$HOME/bitwarden/logs" ]; then
    cd $HOME/bitwarden
    mkdir logs
  fi

  rm -f $HOME/bitwarden/logs/bw-api.log
  touch $HOME/bitwarden/logs/bw-api.log
}

install_packages () {
  cd $HOME/bitwarden/server/src/Api
  dotnet clean
  dotnet restore
}

start_container () {
  bw-start-docker-mssql
  bw-start-docker-azurite
  bw-start-docker-mailcatcher
}

start_project () {
  cd $HOME/bitwarden/server/src/Api
  dotnet run 2>&1 | tee -a $HOME/bitwarden/logs/bw-api.log
}

start_api () {
  ensure_project_ready
  #install_packages
  start_container
  start_project
}

start_api
