#!/usr/bin/env bash

source $APPLICATION_LIB_DIR/windows/windows-core ${1}

if [ ! -d "${PROJECT_PATH}" ]
then
  exit 1
fi

if [ $SUPPORTS_DESTRUCTION == false ] 
then
  log_error "$PROJECT_NAME does not support destruction operations."
  exit 1
fi

log_info "Destroying $PROJECT_NAME"
eval "${DESTROY_COMMAND}"
