#!/usr/bin/env bash

source $HOME/bin/binwarden/windows/windows-core ${1}

if [ $SUPPORTS_EDITING == false ] 
then
  log_error "$PROJECT_NAME does not support editing."
else
  WINDOW_NAME="Editor"
  STARTER_COMMAND="cd ${PROJECT_PATH}; $EDITOR"
  start_window
fi

