#!/usr/bin/env bash

source $APPLICATION_LIB_DIR/windows/windows-core ${1}

mkdir -p $HOME/bitwarden/logs
if [ $SUPPORTS_BUILDING == false ]
then
  log_error "$PROJECT_NAME does not support building."
  exit 1
fi

if [ -z "$SUB_PROJECT_NAME_SHORT" ]
then
  WINDOW_NAME="Build"
else
  WINDOW_NAME="${SUB_PROJECT_NAME_SHORT} Build"
fi

if [ -z "$SUB_PROJECT_PATH" ]
then
  STARTER_COMMAND="cd ${PROJECT_PATH}; ${RUN_COMMAND}"
else
  STARTER_COMMAND="cd ${SUB_PROJECT_PATH}; ${RUN_COMMAND}"
fi

for i in ${!BUILD_DEPS[@]}; do
  b -r ${BUILD_DEPS[$i]}

  # SQL is slow and will need a bit of a head start
  if [[ "${BUILD_DEPS[$i]}" == "MSSQL" ]]
  then
    sleep 30
  fi
done

start_window
