#!/usr/bin/env bash

BITWARDENCLI_APPDATA_DIR=$HOME/.binwarden/.bw-session

export BW_MP=$BINWARDEN_MP
export BW_CLIENTID=$BINWARDEN_CLIENTID
export BW_CLIENTSECRET=$BINWARDEN_CLIENTSECRET

login_to_bw () {
  if ! command -v bw
  then
    $APPLICATION_LIB_DIR/installers/install-bw
  fi
  bw logout
  if [[ -n "${BW_CLIENTSECRET}" ]]; then
    bw login --apikey
    export BINWARDEN_SESSION=$(bw unlock --passwordenv BW_MP --raw)
  else
    export BINWARDEN_SESSION="$(bw login --raw)"
  fi
  bw sync
}

find_config_in_vault () {
  if [ -z "${BINWARDEN_SESSION}" ]; then
    login_to_bw
  fi
  echo $(bw list items --search "bitwarden-environment-setup" --collectionid 'null' --session $BINWARDEN_SESSION)
}

parse_config_item () {
  if [ -z "${BINWARDEN_SESSION}" ]; then
    login_to_bw
  fi
  echo $(find_config_in_vault) | python3 -c "import sys, json; print(json.load(sys.stdin)[0]${1})"
}

parse_config_item_custom_field () {
  if [ -z "${BINWARDEN_SESSION}" ]; then
    login_to_bw
  fi
  echo $(find_config_in_vault) | python3 -c "import sys, json; print(next(cf for cf in json.load(sys.stdin)[0]['fields'] if cf['name'] == '${1}')['value'])"
}

generate_passphrase () {
  if [ -z "${BINWARDEN_SESSION}" ]; then
    login_to_bw
  fi
  OUTPUT_GENERATE_PASSPHRASE="$(bw generate --passphrase --words 3 -c --includeNumber --separator ! --session $BINWARDEN_SESSION)"
}

get_dev_license () {
  if [ -z "${BINWARDEN_SESSION}" ]; then
    login_to_bw
  fi
  bw get attachment dev.cer --itemid 7123e5d3-f837-4a8c-810a-a7ca00fe1fdd --session $BINWARDEN_SESSION
  bw get attachment dev.pfx --itemid 7123e5d3-f837-4a8c-810a-a7ca00fe1fdd --session $BINWARDEN_SESSION
  sudo openssl x509 -inform DER -in dev.cer -out dev.crt
  sudo chmod 644 dev.crt
}

get_dev_license_password () {
  if [ -z "${BINWARDEN_SESSION}" ]; then
    login_to_bw
  fi
  OUTPUT_GET_DEV_LICENSE_PASSWORD="$(bw get password 7123e5d3-f837-4a8c-810a-a7ca00fe1fdd --session $BINWARDEN_SESSION)"
}

get_secrets_json () {
  if [ -z "${BINWARDEN_SESSION}" ]; then
    login_to_bw
  fi
  bw get attachment secrets-for-env-setup.json --itemid d4195f67-dd43-4465-84d7-ae320013e6ff --session $BINWARDEN_SESSION
  mv secrets-for-env-setup.json secrets.json
  bw get attachment additional-keys-for-cloud-services.json --itemid d4195f67-dd43-4465-84d7-ae320013e6ff --session $BINWARDEN_SESSION
}

