#!/usr/bin/env bash

source bw-dev-core

SESSION_PREFIX="✍️"
SESSION_NAME="clients dev"
STARTER_COMMAND="cd $HOME/bitwarden/clients; nvim"
WINDOW_NAME="."

ensure_command_installed nvim
start_session
