#!/usr/bin/env bash

PROJECT=$1

if [[ "$PROJECT" == "all" ]]
then
  read -p "This will completely delete your local environment for all projects. Are you sure? " -n 1 -r
  if [[ $REPLY =~ ^[Yy]$ ]]
  then
    # Server also handles docker for this command
    $HOME/bin/binwarden/windows/destroy-window "server"
    $HOME/bin/binwarden/windows/destroy-window "clients"
    $HOME/bin/binwarden/windows/destroy-window "directory-connector"
    rm -rf $HOME/bitwarden
  fi
  exit 0
fi

read -p "This will completely delete your local $PROJECT environment. Are you sure? " -n 1 -r
if [[ $REPLY =~ ^[Yy]$ ]]
then
  $HOME/bin/binwarden/windows/destroy-window "$PROJECT"
fi


