#!/usr/bin/env bash

PROJECT=$1

read -p "This will completely delete your local $PROJECT environment. Are you sure? " -n 1 -r
echo 
if [[ $REPLY =~ ^[Yy]$ ]]
then
  $HOME/bin/binwarden/windows/destroy-window "$PROJECT"
fi


