#!/usr/bin/env bash

while [[ $# -gt 0 ]] 
do
  case $1 in
    r|run )
      RUN="true"
      shift
      ;;

    s|stop )
      STOP="true"
      shift
      ;;

    d|destroy )
      DESTROY="true"
      shift
      ;;

    *)
      echo "Option ${1} is not supported by this command"
      shift
      ;;
  esac
done

if [ -n "$RUN" ] 
then
  $BINWARDEN_EX_DIR/windows/run-window mssql
fi

if [ -n "$STOP" ] 
then
  $BINWARDEN_EX_DIR/windows/stop-window mssql
fi

if [ -n "$DESTROY" ] 
then
  $BINWARDEN_EX_DIR/windows/destroy-window mssql
fi
