#!/usr/bin/env bash

while [[ $# -gt 0 ]] 
do
  case $1 in
    g|git )
      GIT="true"
      shift
      ;;

    e|edit )
      EDIT="true"
      shift
      ;;

    x|terminal )
      TERMINAL="true"
      shift
      ;;

    *)
      echo "Option ${1} is not supported by this command"
      shift
      ;;
  esac
done

if [ -n "$GIT" ] 
then
  $APPLICATION_LIB_DIR/windows/git-window binwarden
fi

if [ -n "$EDIT" ] 
then
  $APPLICATION_LIB_DIR/windows/editor-window binwarden
fi

if [ -n "$TERMINAL" ] 
then
  $APPLICATION_LIB_DIR/windows/terminal-window binwarden
fi
