#!/usr/bin/env bash

while [[ $# -gt 0 ]] 
do
  case $1 in
    s|stop )
      STOP="true"
      shift
      ;;

    d|destroy )
      DESTROY="true"
      shift
      ;;

    g|git )
      GIT="true"
      shift
      ;;

    e|edit )
      EDIT="true"
      shift
      ;;

    w|web )
      WEB="true"
      shift
      ;;

    x|terminal )
      TERMINAL="true"
      shift
      ;;

    t|test )
      TEST="true"
      shift
      ;;

    *)
      echo "Option ${1} is not supported by this command"
      shift
      ;;
  esac
done

if [ -n "$WEB" ] 
then
  if [ -n "$RUN" ] 
  then
    $APPLICATION_LIB_DIR/windows/run-window web
  fi

  if [ -n "$STOP" ] 
  then
    $APPLICATION_LIB_DIR/windows/stop-window web
  fi

  if [ -n "$DESTROY" ] 
  then
    $APPLICATION_LIB_DIR/windows/destroy-window web
  fi

  if [ -n "$GIT" ] 
  then
    $APPLICATION_LIB_DIR/windows/git-window web
  fi

  if [ -n "$EDIT" ] 
  then
    $APPLICATION_LIB_DIR/windows/editor-window web
  fi
fi

if [ -n "$TERMINAL" ] 
then
  $APPLICATION_LIB_DIR/windows/terminal-window clients
fi

if [ -n "$TEST" ] 
then
  $APPLICATION_LIB_DIR/windows/test-window clients
fi
