#!/usr/bin/env bash

install_dependencies () {
  if [ ! -d "$HOME/bitwarden/clients" ]; then
    bw-scaffold-clients
    exit 0
  fi

  if ! command -v mkcert
  then
    bw-install-mkcert
  fi
}

build_web () {
  install_dependencies
  mkcert -install
  mkcert -cert-file dev-server.local.pem -key-file dev-server.local.pem localhost 127.0.0.1 bitwarden.test
|}

build_web

