#!/usr/bin/env bash

install_dependencies () {
  if ! command -v node
  then
    $HOME/bin/binwarden/installers/bw-install-node
  fi

  mkdir -p $HOME/bitwarden
}

clone_repo () {
  cd $HOME/bitwarden
  git clone git@github.com:bitwarden/directory-connector.git
}

build_dc () {
  cd $HOME/bitwarden/directory-connector
  npm ci
}

setup_directory_connector () {
  install_dependencies
  clone_repo
  build_dc
}

setup_directory_connector
