#!/usr/bin/env bash

source bw-package-manager

install_mkcert () {
  if command -v mkcert
  then
    return 1
  fi

  if [[ "$PACKAGEMANAGER" == "apt" ]]; then
    install_package "libnss3-tools"
    curl -JLO "https://dl.filippo.io/mkcert/latest?for=linux/amd64"
    chmod +x mkcert-v*-linux-amd64
    sudo cp mkcert-v*-linux-amd64 /usr/local/bin/mkcert
  fi

  if [[ "$PACKAGEMANAGER" == "pacman" ]]; then
    install_package mkcert
  fi
}

install_mkcert
