#!/usr/bin/env bash

source bw-package-manager

install_node () {
  if command -v node
  then
    return 1
  fi

  PROFILE=/dev/null bash -c "curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.5/install.sh | bash"
  export NVM_DIR="$HOME/.nvm" 
  [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
  nvm install 'lts/*'
}

install_node

