#!/usr/bin/env bash

PACKAGEMANAGER="unknown"
if command -v apt; then
   PACKAGEMANAGER='apt'
fi
if command -v brew; then
   PACKAGEMANAGER='brew'
fi
if command -v pacman
then
   PACKAGEMANAGER='pacman'
fi

install_package () {
  if [[ "$PACKAGEMANAGER" == "apt" ]]; then
    sudo apt-get -qq -o "DPkg::Lock::Timeout=180" install $1
  fi
  if [[ "$PACKAGEMANAGER" == "brew" ]]; then
    brew install -q $1 
  fi
  if [[ "$PACKAGEMANAGER" == "pacman" ]]; then
    sudo pacman -Syu --noconfirm $1
  fi
}

remove_package () {
  if [[ "$PACKAGEMANAGER" == "apt" ]]; then
    sudo apt-get -qq -o "DPkg::Lock::Timeout=180" remove $1
  fi
  if [[ "$PACKAGEMANAGER" == "brew" ]]; then
    brew uninstall -q $1
  fi
  if [[ "$PACKAGEMANAGER" == "pacman" ]]; then
    sudo pacman -Rsc $1
  fi
}

update_packages () {
  if [[ "$PACKAGEMANAGER" == "apt" ]]; then
    sudo apt-get -qq -o "DPkg::Lock::Timeout=180" update > /dev/null
  fi
  if [[ "$PACKAGEMANAGER" == "brew" ]]; then
    brew update -q
  fi
  if [[ "$PACKAGEMANAGER" == "pacman" ]]; then
    sudo pacman -Syu
    pacman -Rns $(pacman -Qdtq)	
  fi
}

upgrade_packages () {
  if [[ "$PACKAGEMANAGER" == "apt" ]]; then
    sudo -E apt-get -qq -o "Dpkg::Options::=--force-confdef" -o "Dpkg::Options::=--force-confold" -o "DPkg::Lock::Timeout=180" upgrade > /dev/null
  fi
  if [[ "$PACKAGEMANAGER" == "brew" ]]; then
    brew upgrade -q
  fi
  if [[ "$PACKAGEMANAGER" == "pacman" ]]; then
    sudo pacman -Syu
    pacman -Rns $(pacman -Qdtq)	
  fi
}
