#!/usr/bin/bash

source bw-package-manager

install_openssh () {
  if [[ "$PACKAGEMANAGER" == "apt" ]]; then
    install_package openssh-client
    install_package openssh-server
  fi

  if [[ "$PACKAGEMANAGER" == "brew" ]]; then
    install_package openssh
  fi

  if [[ "$PACKAGEMANAGER" == "pacman" ]]; then
    install_package openssh
  fi
}

install_openssh

