#!/usr/bin/bash

source $HOME/bin/binwarden/installers/package-manager

install_gh () {
  if command -v gh
  then
    return 1
  fi

  if [[ "$PACKAGEMANAGER" == "apt" ]]; then
    curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg \
    && sudo chmod go+r /usr/share/keyrings/githubcli-archive-keyring.gpg \
    && echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null \
    && update_packages \
    && install_package gh
  fi

  if [[ "$PACKAGEMANAGER" == "brew" ]]; then
    install_package gh
  fi

  if [[ "$PACKAGEMANAGER" == "pacman" ]]; then
    install_package github-cli
  fi
}

install_gh

