#!/usr/bin/env bash

source $HOME/bin/binwarden/sessions/session-${1}

export WINDOW_NAME="unnamed window"
export STARTER_COMMAND="echo 'No command specified!'"

function start_window () {
  start_session
  if [ $? != 0 ]; then
    tmux has-session -t "$(full_session_name):${WINDOW_NAME}" > /dev/null 2>&1
    if [ $? != 0 ]; then
      log_success "Starting window \"${WINDOW_NAME}\" in session \"$(full_session_name)\""
      success=false
      max_attempts=2
      attempt_num=1
      while [ $success = false ] && [ $attempt_num -le $max_attempts ]; do
        tmux new-window -d -n "${WINDOW_NAME}" -t "$(full_session_name):" "${STARTER_COMMAND}"
        if [ $? -eq 0 ]; then
          success=true
        else
          log_error "Trying \"${WINDOW_NAME}\" again..."
          attempt_num=$(( attempt_num + 1 ))
        fi
      done
      return 0
    else
      log_info "Window \"$(full_session_name): ${WINDOW_NAME}\" is already running."
      return 1
    fi
  fi
}
