#!/usr/bin/env bash

source $HOME/bin/binwarden/windows/windows-core clients
source $HOME/bin/binwarden/builders/build-core web

WINDOW_NAME="Build Web"
PROJECT_PATH="$HOME/bitwarden/clients/apps/web"
STARTER_COMMAND="cd $PROJECT_PATH; npm run build:bit:dev:watch 2>&1 | tee -a $HOME/bitwarden/logs/web.log"

start_api () {
  $HOME/bin/binwarden/builders/build-api
}

start_identity () {
  $HOME/bin/binwarden/builders/build-identity
}

start_web () {
  start_api
  start_identity
  start_window
}

start_web

