#!/usr/bin/env bash

source $HOME/bin/binwarden/windows/windows-core server
source $HOME/bin/binwarden/builders/build-core api

WINDOW_NAME="Build Api"
PROJECT_PATH="$HOME/bitwarden/server/src/Api"
STARTER_COMMAND="cd $PROJECT_PATH; dotnet run 2>&1 | tee -a $HOME/bitwarden/logs/api.log"

start_containers () {
  $HOME/bin/binwarden/builders/build-mssql
  $HOME/bin/binwarden/builders/build-azurite
  $HOME/bin/binwarden/builders/build-mailcatcher
}

start_api () {
  start_containers
  start_window
}

start_api
