#!/usr/bin/env bash

source $HOME/bin/binwarden/sessions/session-server

CONTAINERNAME=bitwardenserver-storage-1
COMPOSEPROFILENAME=storage
LOGFILENAME=bw-docker-azurite.log

enable_logging () {
  if [ ! -d "$HOME/bitwarden/logs" ]; then
    cd $HOME/bitwarden
    mkdir logs
  fi

  rm -f $HOME/bitwarden/logs/$LOGFILENAME
  touch $HOME/bitwarden/logs/$LOGFILENAME
}

start () {
  enable_logging
  cd $HOME/bitwarden/server/dev
  if [ ! "$(docker ps | grep $CONTAINERNAME)" ]; then
    docker compose --profile $COMPOSEPROFILENAME up -d 2>&1 | tee -a $HOME/bitwarden/logs/$LOGFILENAME
  fi
}

start
