#!/usr/bin/env bash

source $HOME/bin/binwarden/installers/package-manager

install_powershell () {
  if command -v pwsh
  then
    install_package "powershell"
    return 1
  fi

  if ! command -v dotnet
  then
    install-dotnet
  fi

  if [[ "$PACKAGEMANAGER" == "brew" ]]; then
    install_package powershell
  fi

  if [[ "$PACKAGEMANAGER" == "apt" ]]; then
    install_package powershell
  fi

  if [[ "$PACKAGEMANAGER" == "pacman" ]]; then
    cd ~
    git clone https://aur.archlinux.org/powershell-bin.git
    cd powershell-bin
    makepkg -sirc
  fi
}

install_powershell
