#!/usr/bin/env bash

source $HOME/bin/binwarden/installers/package-manager

register_microsoft_apt_repo () {
    install_package "wget apt-transport-https software-properties-common"
    source /etc/os-release
    wget -q https://packages.microsoft.com/config/ubuntu/$VERSION_ID/packages-microsoft-prod.deb
    sudo dpkg -i packages-microsoft-prod.deb
    sudo touch /etc/apt/preferences
    echo -e "Package: * \nPin: origin \"packages.microsoft.com\" \nPin-Priority: 1001" | sudo tee -a /etc/apt/preferences > /dev/null
    rm packages-microsoft-prod.deb
    update_packages
}

install_dotnet () {
  if command -v dotnet
  then
    return 1
  fi

  if [[ "$PACKAGEMANAGER" == "apt" ]]; then
    register_microsoft_apt_repo
    install_package "dotnet-sdk-6.0"
    install_package "dotnet-sdk-8.0"
    install_package "aspnetcore-runtime-6.0"
    install_package "aspnetcore-runtime-8.0"
    install_package "dotnet-runtime-6.0"
    install_package "dotnet-runtime-8.0"
  fi
  if [[ "$PACKAGEMANAGER" == "brew" ]]; then
    install_package dotnet@6
    install_package dotnet@8
  fi
  if [[ "$PACKAGEMANAGER" == "pacman" ]]; then
    install_package dotnet-runtime-6.0
    install_package dotnet-sdk-6.0
    install_package aspnet-runtime-6.0

    install_package dotnet-runtime
    install_package dotnet-sdk
    install_package aspnet-runtime
  fi
}

install_dotnet

