#!/usr/bin/env bash

if ! command -v tmux
then
  bw-install-tmux
fi


tmux has-session -t "bw-run-identity" 2>/dev/null

if [ $? != 1 ]; then
  tmux kill-session -t bw-run-identity
fi

tmux new-session -d -s bw-run-identity -n run 'bw-start-identity'
