#!/usr/bin/env bash

source bw-dev-core

source bw-run-api
source bw-run-identity
source bw-run-web

SESSION_PREFIX="🏃"
SESSION_NAME="directory-connector build"
STARTER_COMMAND="bw-start-directory-connector"
WINDOW_NAME="."

start_session
