#!/usr/bin/env bash

if ! command -v tmux
then
  bw-install-tmux
fi


tmux has-session -t "bw-run-api" 2>/dev/null

if [ $? != 1 ]; then
  tmux kill-session -t bw-run-api
fi

tmux new-session -d -s bw-run-api -n run 'bw-start-api'
