#!/usr/bin/env bash

ensure_api_is_running () {
  tmux has-session -t "bw-run-identity" 2>/dev/null

  if [ $? != 0 ]; then
    bw-run-identity
  fi

  tmux has-session -t "bw-run-api" 2>/dev/null

  if [ $? != 0 ]; then
    bw-run-api
  fi
}

ensure_web_is_running () {
  tmux has-session -t "bw-run-web" 2>/dev/null

  if [ $? != 0 ]; then
    bw-run-web
  fi
}

start_directory_connector () {
  if ! command -v tmux
  then
    bw-install-tmux
  fi

  ensure_api_is_running
  ensure_web_is_running

  tmux has-session -t "bw-run-directory-connector" 2>/dev/null

  if [ $? != 0 ]; then
    tmux kill-session -t bw-run-directory-connector
  fi

  tmux new-session -d -s bw-run-directory-connector -n run 'bw-start-directory-connector'
}

start_directory_connector
