#!/usr/bin/env bash

clone_repo () {
  cd $HOME/bitwarden
  git clone git@github.com:bitwarden/sdk.git
  git clone git@github.com:bitwarden/sdk-internal.git
}

setup_sdk () {
  clone_repo
}

setup_sdk
